### ISSUE TITLE
Incompatible with original Roguelike

### ISSUE THREAD

**Issue by ShootToKillSTK** [fnar/minecraft-roguelike#64]
This mod ironically can't run with what it is based off of, aka the original Roguelike mod. Doesn't load bc of duplicate namespaces (See pic)

![image](https://user-images.githubusercontent.com/78947563/142517413-d50e617a-9fbc-4ff2-9191-a3e11f56318f.png)

**Comment by fnar** [comment]
Thanks for the report, but this isn't an issue. This fork is a modified copy of the original, so they completely collide in almost every aspect.

The solution to this problem is to choose strictly one or the other, the original, or this fork.
For details on differences between the two, and migration strategies from the original to this fork: check the wiki provided here in github.

Happy gaming, friend.
