### ISSUE TITLE
Roguelikes and dungeons - crash upon dungeon generation - Mod ver. 2.4.1

### ISSUE THREAD

**Issue by Kiwi-Dude** [fnar/minecraft-roguelike#65]
Experiencing a server crash when encountering Roguelike dungeons. Have them disabled for now, but would like to properly experience the mod. Running on a 7GB Bisect hosting server.

**Comment by Kiwi-Dude** [comment]
[crash-reports_crash-2022-01-04_15.44.48-server.txt](https://github.com/fnar/minecraft-roguelike/files/7828297/crash-reports_crash-2022-01-04_15.44.48-server.txt)

Crash report from the first series of crashes relating to the issue.

**Comment by fnar** [comment]
This might be an OTG issue, but I've seen similar issues solved by setting the `max-tick-time` in the server.properties file to - 1 (to disable the check) or to increase it to something ludicrous (like 999,999).

Certainly I'd love to improve the general performance of this mod, and I'm working at it, especially that heinous Cascading Worldgen lag.

I'll soft close this issue for now since the crash isn't really due to an error in this mod, but due to your server timing out while processing.

Please feel free to re-open it if you need more support or have more evidence of an underlying issue.
